from django.conf.urls import patterns, url

urlpatterns=patterns('diasclases.general.views', 
		url(r'^$', 'view_login', name='vista_principal'),
		url(r'^inicio/$', 'view_index', name='vista_inicio'),
		url(r'^accounts/login/$', 'view_logout', name='vista_login'),
		url(r'^accounts/logout/$', 'view_logout', name='vista_logout'),
		url(r'^nueva-persona/$', 'view_nueva_persona', name='vista_nueva_persona'),
		url(r'^nueva-persona-facsupadmin/$', 'view_nuevo_facilitador', name='vista_nuevo_facilitador'),
		url(r'^editar-persona-facsupadmin/(?P<persona_id>\d+)/$', 'view_editar_facilitador', name='vista_editar_facilitador'),
		url(r'^editar-persona-voluntario/(?P<persona_id>\d+)/$', 'view_editar_voluntario', name='vista_editar_voluntario'),
		url(r'^administration/people/ajaxmuni/$', 'view_people_ajax_municipio', name='vista_ajax_municipio'),
		url(r'^data-centro-ajax/$', 'view_centro_ajax', name='vista_centro_ajax'),
		url(r'^generar-excel/$', 'view_generar_excel', name='vista_generar_excel'),
		url(r'^leer-excel/$', 'view_leer_excel', name='vista_leer_excel'),
		url(r'^consultar-data/$', 'view_consultar_centros', name='vista_consultar_centros'),
		url(r'^consultar-semanas-centro/(?P<centro_voluntario_id>\d+)/$', 'view_consultar_semanas', name='vista_consultar_semanas'),
		url(r'^consultar-data-voluntarios/$', 'view_consultar_voluntarios', name='vista_consultar_voluntarios'),
		url(r'^buscar-usuarios/$', 'view_buscar_usuarios', name='vista_buscar_usuarios'),
		url(r'^buscar-voluntarios/$', 'view_buscar_voluntarios', name='vista_buscar_voluntarios'),
		url(r'^buscar-usuarios-restablecer/$', 'view_buscar_usuarios_restablecer', name='vista_buscar_usuarios_restablecer'),
		url(r'^usuarios-restablecer-clave/(?P<persona_id>\d+)/$', 'view_restablecer_clave', name='vista_restablecer_clave'),
		url(r'^usuarios-ajax-generar-clave/$', 'view_ajax_generar', name='vista_ajax_generar'),
		url(r'^buscar-usuarios-deshabilitar/$', 'view_buscar_usuarios_deshabilitar', name='vista_buscar_usuarios_deshabilitar'),
		url(r'^usuarios-deshabilitar/(?P<persona_id>\d+)/$', 'view_usuario_deshabilitar', name='vista_usuario_deshabilitar'),
		url(r'^usuarios-habilitar/(?P<persona_id>\d+)/$', 'view_usuario_habilitar', name='vista_usuario_habilitar'),
		url(r'^generar-calendario/$', 'view_generar_calendario', name='vista_generar_calendario'),
		url(r'^listar-semana-calendario/$', 'view_listar_calendario', name='vista_listar_calendario'),
		url(r'^quitar-semana-calendario/$', 'view_eliminar_semanacalendario', name='vista_eliminar_semanacalendario'),
		url(r'^quitar-semana-calendario-ajax/(?P<semana_id>\d+)/$', 'view_ajax_eliminar_semanacalendario', name='vista_ajax_eliminar_semanacalendario')

)